home.html
The debug logs worked perfectly! They pointed us exactly to the problem.

In your console screenshot (image_6d9e0b.png), we can see this error:
ReferenceError: user is not defined at fetchEnvironmentData

The cause: The user variable was being defined inside the initHome() function, but fetchEnvironmentData() was trying to update that variable with the API keys without knowing what user was.

The fix: We just need to pull the user object out of localStorage inside the fetchEnvironmentData function before we try to save the new data to it.